import { Router } from 'express';
import { register, login, getProfile, updateProfile, changePassword } from '../controllers/authController';
import { protect } from '../middleware/authMiddleware';
import { upload } from '../utils/upload';
const router = Router();
router.post('/register', register);
router.post('/login', login);
router.get('/profile', protect, getProfile);
router.put('/profile', protect, upload.single('file'), updateProfile);
router.put('/change-password', protect, changePassword);
export default router;
